apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # ✅ Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: octoops-frontend-service
                port:
                  number: 80

          # ✅ Backend APIs
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: octoops-backend-service
                port:
                  number: 3000

          - path: /api/addUser
            pathType: Prefix
            backend:
              service:
                name: octoops-backend-service
                port:
                  number: 3000

          - path: /api/deleteUser
            pathType: Prefix
            backend:
              service:
                name: octoops-backend-service
                port:
                  number: 3000

          - path: /api/health
            pathType: Prefix
            backend:
              service:
                name: octoops-backend-service
                port:
                  number: 3000
